### ISSUE TITLE
HMM Fix NAME field

### ISSUE THREAD

**Issue by jpjarnoux** [mdmparis/defense-finder-models#11]
Hello !

I have been working with your HMMs and I have seen that for some of them the NAME field is filled with only the “gene name” and for others with the name of the HMM_file (System__genename). 
I suggest to keep only one way to fill the NAME field. It seems that for most of them it is only the gene name, so I modified the HMM with the name of the HMM file used, but I am not allowed to push and demand for a pull request.

Thanks

**Comment by jeanrjc** [comment]
Thanks for your feedback, we fixed that in version 1.2.4. 
I'm not sure why you're not able to ask for a PR. I'll check that.
