### ISSUE TITLE
DmdDE and DdmDE labeling in HMM profile (typo?)

### ISSUE THREAD

**Issue by scubalaina** [mdmparis/defense-finder-models#12]
Hi there!
I'm using Defense-Finder for a project, and I noticed in the "DefenseFinder_rules.tsv" table that the system DmdDE requires a gene called DdmDE_DdmE -  the prefix of the system and of the gene's being "Ddm" rather than "Dmd" as the system is called in the system column. I noticed that the HMM profile is also labeled this way (DdmDE_DdmE) and it has the same label within the xml file even though the xml file is titled DmdDE.xml . Is this is a typo and will it impact the ability to detect this system? Or should it still be detectable since the XML file and HMM profile name both contain the typo?

Thanks! :)

**Comment by jeanrjc** [comment]
Thanks for your report, we fixed that in version 1.2.4. Normally, it did not impact the results (the typo were everywhere and thus did not impact the parsing).
