### ISSUE TITLE
Replicate gene names in HMM

### ISSUE THREAD

**Issue by Ge0rges** [mdmparis/defense-finder-models#15]
Hello,

Some of your HMM files are actually concatenated HMMs which each hit (I assume) variants of a same gene. [Here](https://github.com/mdmparis/defense-finder-models/blob/master/profiles/Retron__RT_Tot.hmm) is an example.

It would be useful for the wider use of these models, and for clarity, for the `NAME` field in concatenated HMM to not be identical for all the genes. Even just a numbering suffix would suffice, it is otherwise slightly confusing.

**Comment by Ge0rges** [comment]
To give an example use case where this affects things. `anvio` a popular omics analysis tool has a hard time handling HMMs with multiple genes named identically, and defaults to using the last one.

in this case, and for others who may be using `anvio` I wrote a [script](https://gist.github.com/Ge0rges/16004bdbe358e8d90832685574d323da) which downloads the latest model archive and converts in into a compatible anvio `hmm-source` identical genes in a file a renamed with incrementing suffixes (`_2`, _3`), etc.

**Comment by jeanrjc** [comment]
Thanks for your feedback, we fixed that in version 1.2.4
